PDF_A/1b/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t01.xml
PDF_A/1b/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t02.xml
PDF_A/1b/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t03.xml
PDF_A/1b/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t04.xml

Initial version of validation profiles for PDF/A-1 6.1.3 File trailer

PDF/A-1 6.1.3 File trailer

---

PDF_A/1b/6.2 Graphics/6.2.2 Output intent/verapdf-profile-6-2-2-t01.xml
PDF_A/1b/6.2 Graphics/6.2.2 Output intent/verapdf-profile-6-2-2-t02.xml
PDF_A/1b/6.2 Graphics/6.2.3 Colour spaces/verapdf-profile-6-2-3-t01.xml
PDF_A/1b/6.2 Graphics/6.2.3 Colour spaces/verapdf-profile-6-2-3-t02.xml
PDF_A/1b/6.2 Graphics/6.2.3 Colour spaces/verapdf-profile-6-2-3-t03.xml

- output intent checks
- ICC profiles (input / output)
- use of Device color spaces

initial version of color space profiles

---

PDF_A/1b/6.2 Graphics/6.2.4 Images/verapdf-profile-6-2-4-t01.xml
PDF_A/1b/6.2 Graphics/6.2.4 Images/verapdf-profile-6-2-4-t02.xml
PDF_A/1b/6.2 Graphics/6.2.4 Images/verapdf-profile-6-2-4-t03.xml
PDF_A/1b/6.2 Graphics/6.2.5 Form XObjects/verapdf-profile-6-2-5-t01.xml
PDF_A/1b/6.2 Graphics/6.2.6 Reference XObjects/verapdf-profile-6-2-6-t01.xml
PDF_A/1b/6.2 Graphics/6.2.7 PostScript XObjects/verapdf-profile-6-2-7-t01.xml

Added profiles covering XObject requirements i PDF/A-1

XObject profiles

---

PDF_A/1b/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t04.xml
PDF_A/1b/6.5 Annotations/6.5.2 Annotation types/verapdf-profile-6-5-2-t01.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t01.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t02.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t03.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t04.xml
PDF_A/1b/6.6 Actions/6.6.1 General/verapdf-profile-6-6-1-t01.xml
PDF_A/1b/6.6 Actions/6.6.1 General/verapdf-profile-6-6-1-t02.xml
PDF_A/1b/6.6 Actions/6.6.1 General/verapdf-profile-6-6-1-t03.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t01.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t02.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t03.xml
PDF_A/1b/6.9 Interactive Forms/verapdf-profile-6-9-t01.xml

Validation profiles covering ISO 19005-1:
- Section 6.5 Annotations
- Section 6.6 Actions
- Section 6.9 Interactive forms

Added profiles for Annotations and Actions

---

PDF_A/1b/6.4 Transparency/verapdf-profile-6-4-t02.xml

Change "XObject" to "PDXObject"

Change 6.4-t02 profile

---

PDF_A/1b/6.1 File structure/6.1.7 Stream objects/verapdf-profile-6-1-7-t03.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t01.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t02.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t03.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t04.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t05.xml
PDF_A/1b/6.3 Fonts/6.3.2 Font types/verapdf-profile-6-3-2-t06.xml
PDF_A/1b/6.3 Fonts/6.3.3 Composite fonts/verapdf-profile-6-3-3-t01.xml
PDF_A/1b/6.3 Fonts/6.3.3 Composite fonts/verapdf-profile-6-3-3-t02.xml
PDF_A/1b/6.3 Fonts/6.3.3 Composite fonts/verapdf-profile-6-3-3-t03.xml
PDF_A/1b/6.3 Fonts/6.3.4 Embedded font programs/verapdf-profile-6-3-4-t01.xml
PDF_A/1b/6.3 Fonts/6.3.5 Font subsets/verapdf-profile-6-3-5-t01.xml
PDF_A/1b/6.3 Fonts/6.3.6 Font metics/verapdf-profile-6-3-6-t01.xml

This covers the following clauses from ISO 19005-1:
- 6.3.2 Font types
- 6.3.3 Composite fonts
- 6.3.4 Embedded font programs
- 6.3.5 Font subsets
- 6.3.6 Font metrics

Added font-related validation profiles

---

PDF_A/1b/6.1 File structure/6.1.12 Implementation limits/verapdf-profile-6-1-12-t08.xml
PDF_A/1b/6.1 File structure/6.1.12 Implementation limits/verapdf-profile-6-1-12-t09.xml

- maximum DeviceN components is 8
- maximum nesting level of graphics states is 28

Two more implementation limits profiles

---

PDF_A/1b/6.1 File structure/6.1.10 Filters/verapdf-profile-6-1-10-t02.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t03.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t04.xml

- Added a new validation profile on LZW compression in inline images
- Fixed the condition on LZW compression in general streams
- Added a new validation profile on CID implementation limits

LZW compression for inline images and implementation limits for CID

---

PDF_A/2b/6.1 File structure/6.1.13 Implementation limits/verapdf-profile-6-1-13-t04.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-3B.xml

CosName.origLength -> CosName.internalRepresentation.length()

Remove incorrect property call

---

PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-3B.xml

Updates profile names and model IDs.

Modify general profiles

---

PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-3B.xml
validationProfile.xsd

Done: 
- converted the top level validation profiles (1a, 1b, 2b, 3b); and
- added generated xsd schema for validation profiles.
ToDo:
- conversion of discrete rules.

Created new validation profiles

---

PDF_A/1b/6.7 Metadata/6.7.8/verapdf-profile-6-7-8-t04.xml
PDF_A/1b/6.7 Metadata/6.7.8/verapdf-profile-6-7-8-t05.xml
PDF_A/1b/6.7 Metadata/6.7.8/verapdf-profile-6-7-8-t06.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml

See Isartor test file isartor-6-7-8-t02-fail-f

Changed the description property for Extension schema types from optional to required

---

PDF_A/1b/6.1 File structure/6.1.11 Embedded files/verapdf-profile-6-1-11-t01.xml
PDF_A/1b/6.1 File structure/6.1.11 Embedded files/verapdf-profile-6-1-11-t02.xml
PDF_A/1b/6.2 Graphics/6.2.4 Images/verapdf-profile-6-2-4-t02.xml
PDF_A/1b/6.2 Graphics/6.2.5 Form XObjects/verapdf-profile-6-2-5-t01.xml
PDF_A/1b/6.2 Graphics/6.2.6 Reference XObjects/verapdf-profile-6-2-6-t01.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t01.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t02.xml
PDF_A/1b/6.6 Actions/6.6.2 Trigger events/verapdf-profile-6-6-2-t03.xml
PDF_A/1b/6.9 Interactive Forms/verapdf-profile-6-9-t02.xml
PDF_A/1b/6.9 Interactive Forms/verapdf-profile-6-9-t03.xml
PDF_A/2b/6.2 Graphics/6.2.8 Images/6.2.8.1 General/verapdf-profile-6-2-8-t02.xml
PDF_A/2b/6.2 Graphics/6.2.9 XObjects/6.2.9.1 Form XObjects/verapdf-profile-6-2-9-t01.xml
PDF_A/2b/6.2 Graphics/6.2.9 XObjects/6.2.9.2 Reference XObjects/verapdf-profile-6-2-9-t02.xml
PDF_A/2b/6.4 Interactive Forms/6.4.1 General/verapdf-profile-6-4-1-t01.xml
PDF_A/2b/6.4 Interactive Forms/6.4.1 General/verapdf-profile-6-4-1-t02.xml
PDF_A/2b/6.5 Action/6.5.2 Trigger events/verapdf-profile-6-5-2-t01.xml
PDF_A/2b/6.5 Action/6.5.2 Trigger events/verapdf-profile-6-5-2-t02.xml
PDF_A/2b/6.8 Embedded files/verapdf-profile-6-8-t02.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml

These changes make strickter the checks on presense of certain keys in the dictionaries

Updated profiles accroding to the model changes

---

PDF_UA/1/7.16 Security/verapdf-profile-7-16-t01.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t03-t16.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t17-t20.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t21.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t22.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t23.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t24.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t25.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t26-t28.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t29.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t30.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t31.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t32.xml
PDF_UA/PDF-UA1.xml

Required: https://github.com/veraPDF/veraPDF-validation/pull/312

PDF/UA validation. Lang in marked content.

---

PDF_UA/1/7.1 General/verapdf-profile-7-1-t01.xml
PDF_UA/1/7.1 General/verapdf-profile-7-1-t02.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t33.xml
PDF_UA/1/7.4 Headings/7.4.2 Numbered headings/verapdf-profile-7-4-2-t01.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

Required: https://github.com/veraPDF/veraPDF-validation/pull/318, https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/214

PDF/UA validation. Fix profiles 7.1.1, 7.1.2, 7.2.33, 7.4.2.1

---

PDF_UA/1/7.1 General/verapdf-profile-7-1-t03.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

Required: veraPDF/veraPDF-validation#322, veraPDF/veraPDF-pdfbox-validation#215

PDF/UA validation. Fix rules 7.1.3,7.18.2.1. Add rule 7.18.1.3

---

PDF_UA/1-Human/7.1 General/verapdf-profile-7-1-t13.xml
PDF_UA/1/7.18 Annotations/7.18.1 General/verapdf-profile-7-18-1-t02.xml
PDF_UA/PDFUA-1-Human.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

Required: https://github.com/veraPDF/veraPDF-validation/pull/331, https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/217

PDF/UA validation. Fix rules 7.1.13,7.18.1.2.

---

PDF_UA/1/7.2 Text/verapdf-profile-7-2-t33.xml
PDF_UA/1/7.20 XObjects/verapdf-profile-7-20-t02.xml
PDF_UA/1/7.21 Fonts/7.21.7 Unicode character maps/verapdf-profile-7-21-7-t01.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

Required: https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/219, https://github.com/veraPDF/veraPDF-validation/pull/335, https://github.com/veraPDF/veraPDF-library/pull/1103

PDF/UA validation. Add rule 7.20.2

---

PDF_A/4/6.1 File structure/6.1.12 Document catalog dictionary/verapdf-profile-6-1-12-t01.xml
PDF_A/4/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t04.xml
PDF_A/4/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t05.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.8 Use of ActualText/verapdf-profile-6-2-10-8-t01.xml
PDF_A/4/6.2 Graphics/6.2.5 Extended graphics state/verapdf-profile-6-2-5-t03.xml
PDF_A/4/6.7 Metadata/6.7.3 Version identification/verapdf-profile-6-7-3-t04.xml
PDF_A/4e/6.1 File structure/6.1.6 Stream objects/6.1.6.1 General/verapdf-profile-6-1-6-1-t04.xml

Rules 6.1.3-4, 6.1.3-5, 6.1.6.1-4, 6.1.12-1, 6.2.5-3, 6.2.10.8-1, 6.7.3-4

Add PDF/A-4 profiles.

---

PDF_A/4/6.2 Graphics/6.2.3 Output intent/verapdf-profile-6-2-3-t02.xml
PDF_A/4/6.2 Graphics/6.2.9 Transparency/verapdf-profile-6-2-9-t02.xml
PDF_A/4/6.6 Action/6.6.3 Trigger events/verapdf-profile-6-6-3-t01.xml
PDF_A/4/6.9 Embedded files/verapdf-profile-6-9-t01.xml
PDF_A/4e/6.1 File structure/6.1.6 Stream objects/6.1.6.1 General/verapdf-profile-6-1-6-1-t03.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

Add PDF/A-4 rules.

---

PDF_A/1b/6.7 Metadata/6.7.9 Validation/verapdf-profile-6-7-9-t01.xml
PDF_A/1b/6.7 Metadata/6.7.9 Validation/verapdf-profile-6-7-9-t02.xml
PDF_A/2b/6.1 File structure/6.1.7 Stream objects/verapdf-profile-6-1-7-t03.xml
PDF_A/2b/6.6 Metadata/6.6.2 Metadata streams/6.6.2.1 General/verapdf-profile-6-6-2-1-t04.xml
PDF_A/2b/6.6 Metadata/6.6.2 Metadata streams/6.6.2.3 Schemas/verapdf-profile-6-6-2-3-t07.xml
PDF_A/4/6.1 File structure/6.1.3 File trailer/verapdf-profile-6-1-3-t01.xml
PDF_A/4/6.1 File structure/6.1.6 Stream objects/6.1.6.1 General/verapdf-profile-6-1-6-1-t02.xml
PDF_A/4/6.7 Metadata/6.7.2 Metadata streams/6.7.2.1 General/verapdf-profile-6-7-2-1-t04.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

6.1.3-1, 6.1.6.1-2, 6.1.7-3, 6.6.2.1-4, 6.6.2.3-7, 6.7.2.1-4, 6.7.9-1, 6.7.9-2

Fix error messages for rules

---

PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.8 Use of ActualText/verapdf-profile-6-2-10-8-t01.xml
PDF_A/4/6.7 Metadata/6.7.3 Version identification/verapdf-profile-6-7-3-t05.xml
PDF_A/4/6.9 Embedded files/verapdf-profile-6-9-t04.xml
PDF_A/4f/6.9 Embedded files/verapdf-profile-6-9-t05.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

PDF/A-4 validation. Add rules 6.7.3-5, 6.9-4.

---

PDF_A/2b/6.5 Action/6.5.1 General/verapdf-profile-6-5-1-t01.xml
PDF_A/4/6.2 Graphics/6.2.4 Colour spaces/6.2.4.2 ICCBased colour spaces/verapdf-profile-6-2-4-2-t03.xml
PDF_A/4/6.2 Graphics/6.2.4 Colour spaces/6.2.4.3 Uncalibrated Device colour spaces/verapdf-profile-6-2-4-3-t02.xml
PDF_A/4/6.2 Graphics/6.2.4 Colour spaces/6.2.4.3 Uncalibrated Device colour spaces/verapdf-profile-6-2-4-3-t03.xml
PDF_A/4/6.2 Graphics/6.2.5 Extended graphics state/verapdf-profile-6-2-5-t01.xml
PDF_A/4/6.2 Graphics/6.2.5 Extended graphics state/verapdf-profile-6-2-5-t02.xml
PDF_A/4/6.2 Graphics/6.2.5 Extended graphics state/verapdf-profile-6-2-5-t03.xml
PDF_A/4/6.3 Annotations/6.3.3 Annotation appearances/verapdf-profile-6-3-3-t01.xml
PDF_A/4/6.6 Action/6.6.1 General/verapdf-profile-6-6-1-t01.xml
PDF_A/4/6.7 Metadata/6.7.2 Metadata streams/6.7.2.1 General/verapdf-profile-6-7-2-1-t05.xml
PDF_A/4/6.7 Metadata/6.7.3 Version identification/verapdf-profile-6-7-3-t01.xml
PDF_A/4e/6.6 Action/6.6.1 General/verapdf-profile-6-6-1-t01.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

Fix rules 6.3.3-1, 6.6.1-1, 6.7.3-1

PDF/A-4 validation. Add rules 6.2.4.2-3, 6.2.4.3-2, 6.2.4.3-3, 6.7.2.1-5

---

PDF_UA/WCAG-21-Complete.xml
PDF_UA/WCAG-21-Dev.xml
PDF_UA/WCAG-21.xml

WCAG validation. Add rules 4.1.2-20, 4.1.2.1-13

---

PDF_A/2b/6.2 Graphics/6.2.4 Colour spaces/6.2.4.4 Separation and DeviceN colour spaces/verapdf-profile-6-2-4-4-t02.xml
PDF_A/2b/6.2 Graphics/6.2.8 Images/6.2.8.3 JPEG2000/verapdf-profile-6-2-8-3-t02.xml
PDF_A/2b/6.2 Graphics/6.2.8 Images/6.2.8.3 JPEG2000/verapdf-profile-6-2-8-3-t03.xml
PDF_A/2b/6.2 Graphics/6.2.8 Images/6.2.8.3 JPEG2000/verapdf-profile-6-2-8-3-t04.xml
PDF_A/4/6.2 Graphics/6.2.4 Colour spaces/6.2.4.4 Separation and DeviceN colour spaces/verapdf-profile-6-2-4-4-t02.xml
PDF_A/4/6.2 Graphics/6.2.7 Images/6.2.7.3 JPEG2000/verapdf-profile-6-2-7-3-t02.xml
PDF_A/4/6.2 Graphics/6.2.7 Images/6.2.7.3 JPEG2000/verapdf-profile-6-2-7-3-t03.xml
PDF_A/4/6.2 Graphics/6.2.7 Images/6.2.7.3 JPEG2000/verapdf-profile-6-2-7-3-t04.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

PDF/A validation. Fix rules 6.2.4.4-2, 6.2.7.3-2 - 6.2.7.3-4

---

PDF_A/2b/6.2 Graphics/6.2.11 Fonts/6.2.11.3 Composite fonts/verapdf-profile-6-2-11-3-t02.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.3 Composite fonts/6.2.10.3.2 CIDFonts/verapdf-profile-6-2-10-3-2-t01.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml
PDF_UA/1/7.21 Fonts/7.21.3 Composite fonts/7.21.3.2 CIDFonts/verapdf-profile-7-21-3-2-t01.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

PDF/UA and WCAG validation. Fix rule 7.21.3.2-1

PDF/A validation. Fix rules 6.2.11.3-2 and 6.2.10.3.2-1

---

PDF_UA/WCAG-21-Complete.xml
PDF_UA/WCAG-21-Dev.xml
PDF_UA/WCAG-21.xml

Add rules about different styles, merged cells and struct tree root

WCAG validation. Fix rule about repeated characters

---

PDF_UA/WCAG-21-Complete.xml

Add error arguments for existing rules

WCAG validation. Add rules about TOCIs

---

PDF_A/1a/6.8 Logical Structure/6.8.2 Tagged PDF/6.8.2.2 Mark information dictionary/verapdf-profile-6-8-2-2-t01.xml
PDF_A/1b/6.7 Metadata/6.7.11 Version and conformance level identification/verapdf-profile-6-7-11-t04.xml
PDF_A/1b/6.7 Metadata/6.7.2 Properties/verapdf-profile-6-7-2-t01.xml
PDF_A/1b/6.7 Metadata/6.7.2 Properties/verapdf-profile-6-7-2-t02.xml
PDF_A/1b/6.7 Metadata/6.7.5 XMP Header/verapdf-profile-6-7-5-t01.xml
PDF_A/1b/6.7 Metadata/6.7.5 XMP Header/verapdf-profile-6-7-5-t02.xml
PDF_A/1b/6.7 Metadata/6.7.9 Validation/verapdf-profile-6-7-9-t01.xml
PDF_A/1b/6.7 Metadata/6.7.9 Validation/verapdf-profile-6-7-9-t02.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml

Rename rule 6.8.2-1 to 6.8.2.2-1

PDF/A-1 validation. Update rule 6.7.11-4

---

PDF_A/1b/6.2 Graphics/6.2.3 Colour spaces/6.2.3.2 ICCBased colour spaces/verapdf-profile-6-2-3-2-t01.xml
PDF_A/2b/6.2 Graphics/6.2.3 Output intent/verapdf-profile-6-2-3-t01.xml
PDF_A/2b/6.2 Graphics/6.2.4 Colour spaces/6.2.4.2 ICCBased colour spaces/verapdf-profile-6-2-4-2-t01.xml
PDF_A/4/6.2 Graphics/6.2.3 Output intent/verapdf-profile-6-2-3-t01.xml
PDF_A/4/6.2 Graphics/6.2.4 Colour spaces/6.2.4.2 ICCBased colour spaces/verapdf-profile-6-2-4-2-t01.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

for rules 6.2.3.2-1(PDF/A-1),6.2.3-1,6.2.4.2-1(PDF/A-2,3,4)

PDF/A validation. Update error messages

---

PDF_A/1b/6.7 Metadata/6.7.8 Extension schemas/verapdf-profile-6-7-8-t06.xml
PDF_A/2b/6.6 Metadata/6.6.2 Metadata streams/6.6.2.3 Schemas/6.6.2.3.3 Extension schema container schemas/verapdf-profile-6-6-2-3-3-t05.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml

PDF/A-2,3 validation. Update rule 6.6.2.3.3-5

PDF/A-1 validation. Update rule 6.7.8-6.

---

PDF_A/1b/6.3 Fonts/6.3.5 Font subsets/verapdf-profile-6-3-5-t03.xml
PDF_A/1b/6.5 Annotations/6.5.3 Annotation dictionaries/verapdf-profile-6-5-3-t03.xml
PDF_A/2b/6.2 Graphics/6.2.11 Fonts/6.2.11.4 Embedding/6.2.11.4.2 Subset embedding/verapdf-profile-6-2-11-4-2-t02.xml
PDF_A/PDFA-1A.xml
PDF_A/PDFA-1B.xml
PDF_A/PDFA-2A.xml
PDF_A/PDFA-2B.xml
PDF_A/PDFA-2U.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_UA/1/7.21 Fonts/7.21.4 Embedding/7.21.4.2 Subset embedding/verapdf-profile-7-21-4-2-t02.xml
PDF_UA/PDFUA-1.xml
PDF_UA/WCAG-21-Complete.xml

Update rules 6.3.5-3,6.5.3-3(PDF/A-1), 6.2.11.4.2-2(PDF/A-2)

---

PDF_A/3b/6.8 Embedded files/verapdf-profile-6-8-t03.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.6 Character encodings/verapdf-profile-6-2-10-6-t01.xml
PDF_A/PDFA-3A.xml
PDF_A/PDFA-3B.xml
PDF_A/PDFA-3U.xml
PDF_A/PDFA-4.xml
PDF_A/PDFA-4E.xml
PDF_A/PDFA-4F.xml

6.2.10.6-1(PDF/A-4)
6.8-3(PDF/A-3)

PDF/A. Update rule descriptions

---

PDF_UA/1/7.1 General/verapdf-profile-7-1-t12.xml
PDF_UA/2/8.2 Logical structure/8.2.1 General/verapdf-profile-8-2-1-t02.xml

PDF/UA-1(7.1-12),PDF/UA-2(8.2.1-2)

PDF/UA. Add rules about struct tree root parent.

---

PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.8 Use of ActualText/verapdf-profile-6-2-10-8-t01.xml
PDF_UA/1/7.1 General/verapdf-profile-7-1-t01.xml
PDF_UA/1/7.1 General/verapdf-profile-7-1-t02.xml
PDF_UA/1/7.1 General/verapdf-profile-7-1-t03.xml
PDF_UA/2/8.2 Logical structure/8.2.2 Real content/verapdf-profile-8-2-2-t01.xml
PDF_UA/2/8.4 Text representation for content/8.4.3 Replacements and alternatives for text/verapdf-profile-8-4-3-t02.xml
PDF_UA/2/8.4 Text representation for content/8.4.3 Replacements and alternatives for text/verapdf-profile-8-4-3-t03.xml
PDF_UA/2/8.5 Real content without textual semantics/8.5.1 General/verapdf-profile-8-5-1-t01.xml

PDF/UA-1(7.1-1 - 7.1-2), PDF/UA-2(8.2.2-1, 8.5.1-1)

PDF/UA. Update rules about tagged content

---

PDF_A/2b/6.4 Interactive Forms/6.4.1 General/verapdf-profile-6-4-1-t01.xml
PDF_A/2b/6.4 Interactive Forms/6.4.1 General/verapdf-profile-6-4-1-t02.xml
PDF_A/2u/6.2 Graphics/6.2.11 Fonts/6.2.11.7 Unicode character maps/6.2.11.7.2 Level A and Level U conformance/verapdf-profile-6-2-11-7-2-t02.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.6 Character encodings/verapdf-profile-6-2-10-6-t01.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.7 Unicode character maps/verapdf-profile-6-2-10-7-t01.xml
PDF_A/4/6.2 Graphics/6.2.10 Fonts/6.2.10.8 Use of ActualText/verapdf-profile-6-2-10-8-t01.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t13.xml
PDF_UA/1/7.2 Text/verapdf-profile-7-2-t14.xml
PDF_UA/1/7.21 Fonts/7.21.7 Unicode character maps/verapdf-profile-7-21-7-t02.xml
PDF_UA/2/8.10 Forms/8.10.2 Context/8.10.2.3 Contents entry/verapdf-profile-8-10-2-3-t02.xml
PDF_UA/2/8.2 Logical structure/8.2.5 Additional requirements for specific structure types/8.2.5.26 Table (Table, TR, TH, TD, THead, TBody, TFoot)/verapdf-profile-8-2-5-26-t02.xml
PDF_UA/2/8.4 Text representation for content/8.4.3 Replacements and alternatives for text/verapdf-profile-8-4-3-t02.xml
PDF_UA/2/8.4 Text representation for content/8.4.3 Replacements and alternatives for text/verapdf-profile-8-4-3-t03.xml
PDF_UA/2/8.4 Text representation for content/8.4.5 Fonts/8.4.5.7 Character encodings/verapdf-profile-8-4-5-7-t01.xml
PDF_UA/2/8.4 Text representation for content/8.4.5 Fonts/8.4.5.8 Unicode character maps/verapdf-profile-8-4-5-8-t02.xml
PDF_UA/2/8.9 Annotations/8.9.2 Semantics and content/8.9.2.2 Annotations as artifacts/verapdf-profile-8-9-2-2-t02.xml
PDF_UA/WCAG/PDF_UA/1/verapdf-profile-7-2-t13.xml
PDF_UA/WCAG/PDF_UA/1/verapdf-profile-7-2-t14.xml
README.md

PDF/UA-2 (8.2.5.26-2, 8.4.3-2, 8.4.3-3, 8.4.5.7-1, 8.4.5.8-2, 8.9.2.2-2, 8.10.2.3-2), PDF/UA-1 (7.2-13, 7.2-14, 7.21.7-2),
PDF/A-4 (6.2.10.6-1, 6.2.10.7-1, 6.2.10.8-1),
PDF/A-2 (6.4.1-1, 6.4.1-2), PDF/A-2U (6.2.11.7.2-2). Update readme

Update error messages in PDF/A and PDF/UA profiles.
